/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId */

#ifndef _Included_io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId
#define _Included_io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId
 * Method:    send
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lio/netty/channel/Channel;)I
 */
JNIEXPORT jint JNICALL Java_io_github_gdrfgdrf_cuteverification_web_minecraft_client_impl_fabric_natives_DeviceId_send
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
